apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-airport-paas
  labels:
    app: argo-airport-paas
spec:
  replicas: 5
  selector:
    matchLabels:
      app: argo-airport-paas
  template:
    metadata:
      labels:
        app: argo-airport-paas
    spec:
      containers:
        - name: argo-airport-paas
          image: ghcr.io/3kmfi6hp/argo-airport-paas:main
          ports:
            - containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: config-env
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "1"
              memory: "1024Mi"
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 3
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: argo-airport-paas-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: argo-airport-paas
